<a href="https://colab.research.google.com/github/abdulazizkomilov/Data-Science/blob/main/bolean_indek.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
names = np.array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Mirzabek', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U8')

In [5]:
data = np.random.randn(7, 4)
data

array([[ 0.93446034, -0.62816683, -0.07651945,  1.40812817],
       [ 1.75256986, -2.26355012,  1.46941674,  0.87071357],
       [-0.29877088,  1.70057914,  0.15190711, -0.23664418],
       [-0.48006671, -1.20501022,  0.38675199,  0.30910987],
       [ 0.32466266, -2.50518941,  1.16287971,  0.63958517],
       [-0.52420398,  0.6440579 , -1.07813263,  1.08301061],
       [ 0.81451347,  1.34697516, -0.64594248,  0.48597371]])

In [7]:
data[~(names == 'Hasan')]

array([[ 1.75256986, -2.26355012,  1.46941674,  0.87071357],
       [-0.29877088,  1.70057914,  0.15190711, -0.23664418],
       [-0.48006671, -1.20501022,  0.38675199,  0.30910987],
       [-0.52420398,  0.6440579 , -1.07813263,  1.08301061],
       [ 0.81451347,  1.34697516, -0.64594248,  0.48597371]])

In [19]:
mask = (names=='Hasan') | (names=='Husan')
mask

array([ True,  True, False, False,  True, False, False])

In [20]:
data[mask]

array([[ 0.93446034, -0.62816683, -0.07651945,  1.40812817],
       [ 1.75256986, -2.26355012,  1.46941674,  0.87071357],
       [ 0.32466266, -2.50518941,  1.16287971,  0.63958517]])

In [22]:
data[data<0] = 0
data

array([[0.93446034, 0.        , 0.        , 1.40812817],
       [1.75256986, 0.        , 1.46941674, 0.87071357],
       [0.        , 1.70057914, 0.15190711, 0.        ],
       [0.        , 0.        , 0.38675199, 0.30910987],
       [0.32466266, 0.        , 1.16287971, 0.63958517],
       [0.        , 0.6440579 , 0.        , 1.08301061],
       [0.81451347, 1.34697516, 0.        , 0.48597371]])